version: '3.4'
services:
  tutorial-share-share:
    image: alfresco-share-tutorial-share:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: tutorial-share-acs
      REPO_PORT: 8080
    ports:
      - "8180:8080"
      - "9898:8888"
# Optional
#  tutorial-share-acs:
#    image: alfresco/alfresco-content-repository-community:7.0.0
#    environment:
#      JAVA_OPTS: "
#                -Ddb.driver=org.postgresql.Driver
#                -Ddb.username=alfresco
#                -Ddb.password=alfresco
#                -Ddb.url=jdbc:postgresql://tutorial-share-postgres:5432/alfresco
#                -Dsolr.host=tutorial-share-ass
#                -Dsolr.port=8983
#                -Dsolr.secureComms=none
#                -Dsolr.base.url=/solr
#                -Dindex.subsystem.name=solr6
#                -Dcsrf.filter.enabled=false
#                -Dmessaging.broker.url=\"vm://localhost?broker.persistent=false\"
#                -Dtransform.service.enabled=false
#                -Dlocal.transform.service.enabled=false
#                -Dlegacy.transform.service.enabled=false
#                -Dencryption.keystore.type=JCEKS
            -Dencryption.cipherAlgorithm=AES/CBC/PKCS5Padding
            -Dencryption.keyAlgorithm=AES
            -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
            -Dmetadata-keystore.password=mp6yc0UD9e
            -Dmetadata-keystore.aliases=metadata
            -Dmetadata-keystore.metadata.password=oKIWzVdEdA
            -Dmetadata-keystore.metadata.algorithm=AES
#                "
#    ports:
#      - "8080:8080"
#    volumes:
#      - tutorial-share-acs-volume:/usr/local/tomcat/alf_data
#    depends_on:
#      - tutorial-share-postgres
#  tutorial-share-postgres:
#    image: postgres:9.6
#    environment:
#      POSTGRES_DB: alfresco
#      POSTGRES_USER: alfresco
#      POSTGRES_PASSWORD: alfresco
#    command: postgres -c max_connections=300 -c log_min_messages=LOG
#    ports:
#      - "5555:5432"
#    volumes:
#      - tutorial-share-db-volume:/var/lib/postgresql/data
#  tutorial-share-ass:
#    image: alfresco/alfresco-search-services:1.2.0
#    environment:
#      SOLR_ALFRESCO_HOST: tutorial-share-acs
#      SOLR_ALFRESCO_PORT: 8080
#      SOLR_SOLR_HOST: tutorial-share-ass
#      SOLR_SOLR_PORT: 8983
#      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
#    ports:
#      - "8983:8983"
#    volumes:
#      - tutorial-share-ass-volume:/opt/alfresco-search-services/contentstore
#      - tutorial-share-ass-volume:/opt/alfresco-search-services/data
#volumes:
#  tutorial-share-acs-volume:
#    external: true
#  tutorial-share-db-volume:
#    external: true
#  tutorial-share-ass-volume:
#    external: true
